import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<UserProvider>
				<body>
					<header className="w-screen ">
						<nav className="flex justify-center gap-5">
							<Link className="text-slate-400 hover:text-slate-300" href={"/"}>
								Home
							</Link>
							<Link className="text-slate-400 hover:text-slate-300" href={"/youtrack"}>
								Youtrack
							</Link>
							<Link className="text-slate-400 hover:text-slate-300" href={"/asana"}>
								Asana
							</Link>
							<a href="/api/auth/login">Login</a>
						</nav>
					</header>

					{children}
				</body>
			</UserProvider>
		</html>
	);
}
